# Generated by Django 5.0.6 on 2024-06-08 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id_User', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id_APIKeys', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=500)),
                ('secret_key', models.CharField(max_length=500)),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Listeners',
            fields=[
                ('id_Listeners', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.BigIntegerField(default=0)),
                ('side', models.CharField(max_length=50)),
                ('id_APIKeys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.apikeys')),
            ],
        ),
    ]
