# Generated by Django 5.0.6 on 2024-06-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='id_User',
            new_name='id_Accounts',
        ),
        migrations.RenameField(
            model_name='apikeys',
            old_name='id_User',
            new_name='id_Accounts',
        ),
    ]
