# Generated by Django 5.0.6 on 2024-06-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_id_user_accounts_id_accounts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikeys',
            old_name='key',
            new_name='base_key',
        ),
    ]
